DROP TABLE MODEL1;
DROP TABLE MODEL2;

CREATE TABLE MODEL1 (
  ID           BIGINT        NOT NULL AUTO_INCREMENT,
  NOM 	       VARCHAR(255)  NOT NULL,
  UNEDATE      DATE 		 NOT NULL,
  VAL          VARCHAR(255)  NOT NULL,
  PRIMARY KEY (ID)
 );
 
 CREATE TABLE MODEL2 (
  ID           BIGINT        NOT NULL AUTO_INCREMENT,
  NOM 	       VARCHAR(255)  NOT NULL,
  UNEDATE      DATE 		 NOT NULL,
  VAL          VARCHAR(255)  NOT NULL,
  PRIMARY KEY (ID)
 );

DELETE FROM MODEL1;
DELETE FROM MODEL2;

 


